# -*- coding: utf-8 -*-
"""Advanced course

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cjPY_i7SsEK3f2SM2WfPmXsU-TUTt1ho

SINGLE PLOTS pH SCREENING - Figure 5
"""

from google.colab import files
import os
import pandas as pd

print("👉 Select your merged CSV files (you can pick multiple).")
uploaded = files.upload()  # choose: phytic_pH_screen_raw_compiled.csv, phytic_pH88_triplicates_compiled.csv, phytic_pH88_med_series_compiled.csv

# Build full paths under /content
INPUT_FILES = [os.path.join("/content", name) for name in uploaded.keys()]

# Quick sanity checks
print("\nFiles found:")
for p in INPUT_FILES:
    exists = os.path.exists(p)
    print(f"  {p}  ->  {'OK' if exists else 'MISSING'}")
    if exists:
        try:
            head = pd.read_csv(p, nrows=3)
            cols = list(head.columns)
            print(f"     Columns: {cols}")
        except Exception as e:
            print(f"     (Could not preview: {e})")

"""SUMMARY pH SCREENING - Figure 6

"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Map Test IDs -> pH
ph_map = {1:3.0, 2:4.5, 3:6.0, 4:7.0, 5:8.0, 6:8.8, 7:10.0}

df = pd.DataFrame({
    "TestID": [1,2,3,4,5,6,7],
    "pH": [ph_map[i] for i in range(1,8)],
    "RT": [7.05,10.24,9.53,9.68,7.29,7.27,2.40],
    "NL": [1.08e4,4.33e4,2.44e5,2.07e5,8.06e6,3.94e6,2.00e5],
    "USP_TF": [1.42,2.04,2.41,2.46,2.21,2.42,3.68]
})

# Compute log10(NL) for dynamic range
df["logNL"] = np.log10(df["NL"])

# Optional: sort by pH to ensure monotonic x-axis
df = df.sort_values("pH")

# --- Colors (distinct per figure) ---
color_nl  = "#1f77b4"  # blue
color_rt  = "#2ca02c"  # green
color_tf  = "#d62728"  # red

# --- Fig 1: log10(NL) vs pH ---
plt.figure(figsize=(6.5,4.2))
plt.plot(df["pH"], df["logNL"], marker="o", linewidth=2, color=color_nl)
plt.xlabel("pH")
plt.ylabel("log10(NL)")
plt.title("Signal Intensity vs pH")
plt.grid(True, linestyle="--", alpha=0.3)
plt.tight_layout()
plt.savefig("pH_vs_logNL.png", dpi=300)
plt.show()

# --- Fig 2: RT vs pH ---
plt.figure(figsize=(6.5,4.2))
plt.plot(df["pH"], df["RT"], marker="o", linewidth=2, color=color_rt)
plt.xlabel("pH")
plt.ylabel("Retention Time (min)")
plt.title("Retention Time vs pH")
plt.grid(True, linestyle="--", alpha=0.3)
plt.tight_layout()
plt.savefig("pH_vs_RT.png", dpi=300)
plt.show()

# --- Fig 3: USP TF vs pH ---
plt.figure(figsize=(6.5,4.2))
plt.plot(df["pH"], df["USP_TF"], marker="o", linewidth=2, color=color_tf)
plt.xlabel("pH")
plt.ylabel("USP Tailing Factor")
plt.title("Peak Symmetry (USP TF) vs pH")
plt.grid(True, linestyle="--", alpha=0.3)
plt.tight_layout()
plt.savefig("pH_vs_TF.png", dpi=300)
plt.show()

print("Saved: pH_vs_logNL.png, pH_vs_RT.png, pH_vs_TF.png")

"""SINGLE PLOTS FOR PH SCREENING,pH 8.8 TRIPLICATES, MEDRONIC ACID TRIPLICATES 5 mM. Figure 5, 7 and single plots of medronic acid 5 mM"""

import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from itertools import cycle

# ---------- CONFIG ----------
INPUT_FILES = [
    "/content/phytic_pH_screen_raw_compiled.csv",
    "/content/phytic_pH88_triplicates_compiled.csv",
    "/content/phytic_pH88_med_series_compiled.csv",
]
OUTPUT_BASEDIR = "/content/phytic_outputs"

# Processing parameters
BASELINE_WINDOW_POINTS = 101
SMOOTH_WINDOW_POINTS   = 7
TAILING_FRACTION       = 0.05
MIN_POINTS_REQUIRED    = 50

# Color cycle (use Matplotlib default, or replace with your own hex list)
COLOR_CYCLE = cycle(plt.rcParams["axes.prop_cycle"].by_key()["color"])
# Example custom palette:
# COLOR_CYCLE = cycle(["#1f77b4","#ff7f0e","#2ca02c","#d62728","#9467bd","#8c564b"])

# ---- Optional explicit titles per file (edit as you like) ----
CUSTOM_TITLES = {
    # pH screen (single runs at multiple pH)
    "pH45_good.csv": "pH 4.5",
    "Phytic_acid_20250916073744_pH10_good.csv": "pH 10.0",
    "std500pH3_20251014.csv": "pH 3.0",
    "std500pH6_20251014_good.csv": "pH 6.0",
    "std500pH7_20251014_good.csv": "pH 7.0",
    "std500pH8_2_20251017_good.csv": "pH 8.0",
    "std500pH88_20251017_good.csv": "pH 8.8",

    # pH 8.8 triplicates
    "std500pH88_20251024_tri1.csv": "Phytic acid 500 µg/mL — pH 8.8 — Rep 1",
    "std500pH88_20251024_tri2.csv": "Phytic acid 500 µg/mL — pH 8.8 — Rep 2",
    "std500pH88_20251024_tri3.csv": "Phytic acid 500 µg/mL — pH 8.8 — Rep 3",

    # pH 8.8 med series
    "std500pH88_20251024_med1.csv": "Medronic acid 0.5 mM - Sample 1",
    "std500pH88_20251024_med2.csv": "Medronic acid 0.5 mM - Sample 2",
    "std500pH88_20251024_med3.csv": "Medronic acid 0.5 mM - Sample 3",
}


def pretty_title(fname, inferred_pH=None, series=""):
    """Return a clean title string for the plot."""
    if fname in CUSTOM_TITLES:
        return CUSTOM_TITLES[fname]
    stem = os.path.splitext(fname)[0].replace("_", " ")
    if inferred_pH is not None and not (isinstance(inferred_pH, float) and np.isnan(inferred_pH)):
        stem += f" | pH {inferred_pH:g}"
    if series:
        stem += f" | {series}"
    return stem

# ---------- UTILITIES ----------

def infer_ph_from_name(name: str):
    m = re.search(r'(?i)pH\s*([0-9]{1,2})(?:[._-]?([0-9]))?', name)
    if m:
        whole, frac = m.group(1), m.group(2)
        if frac is None:
            return float(whole)
        if len(whole) == 2:  # "45"->4.5, "88"->8.8
            return float(f"{whole[0]}.{frac}")
        return float(f"{whole}.{frac}")
    return None

def parse_compiled_chrom_file(path):
    raw = pd.read_csv(path)
    if "source_file" not in raw.columns or "CHROMATOGRAM" not in raw.columns:
        raise ValueError(f"{path}: missing required columns 'source_file' and/or 'CHROMATOGRAM'.")
    results = {}
    for fname, grp in raw.groupby("source_file", sort=False):
        lines = grp["CHROMATOGRAM"].astype(str).tolist()
        # find "Time(min),..." header line
        start_idx = 0
        for i in range(min(10, len(lines))):
            if "Time" in lines[i] and "," in lines[i]:
                start_idx = i + 1
                break
        t, y = [], []
        for line in lines[start_idx:]:
            if "," not in line:
                continue
            a, b = line.split(",", 1)
            try:
                t.append(float(a)); y.append(float(b))
            except ValueError:
                pass
        if len(t) < MIN_POINTS_REQUIRED:
            continue
        df = pd.DataFrame({"time_min": np.array(t), "intensity": np.array(y)})
        df["inferred_pH"] = grp["inferred_pH"].iloc[0] if "inferred_pH" in grp.columns else infer_ph_from_name(fname)
        df["series"] = grp["series"].iloc[0] if "series" in grp.columns else ""
        results[fname] = df
    return results

def rolling_min_baseline(y, window):
    s = pd.Series(y)
    base = s.rolling(max(3, window), min_periods=1, center=True).min()
    base = base.rolling(max(3, window//5), min_periods=1, center=True).mean()
    return base.values

def smooth_ma(y, window):
    if window <= 1:
        return y
    w = np.ones(window) / window
    return np.convolve(y, w, mode="same")

def usp_tailing(time, y_proc, frac=0.05):
    y = np.asarray(y_proc); t = np.asarray(time)
    if y.size < 3 or np.max(y) <= 0:
        return None
    idx_max = int(np.argmax(y))
    apex_t = float(t[idx_max]); apex_h = float(y[idx_max])
    level = float(frac * apex_h)

    # Left crossing
    i = idx_max
    while i > 0 and y[i] > level: i -= 1
    left_t = float(t[0]) if i == 0 else (
        float(t[i]) if t[i+1] == t[i] or y[i+1] == y[i]
        else float(t[i] + (level - y[i]) * (t[i+1] - t[i]) / (y[i+1] - y[i]))
    )

    # Right crossing
    i = idx_max
    n = len(y)
    while i < n-1 and y[i] > level: i += 1
    right_t = float(t[-1]) if i == n-1 else (
        float(t[i]) if y[i] == y[i-1]
        else float(t[i-1] + (level - y[i-1]) * (t[i] - t[i-1]) / (y[i] - y[i-1]))
    )

    W05   = right_t - left_t
    flead = apex_t - left_t
    tail  = float("nan") if flead <= 0 else W05 / (2.0 * flead)
    return {
        "apex_time_min": apex_t,
        "apex_height": apex_h,
        "level_fraction": float(frac),
        "level_value": level,
        "left_time_min": left_t,
        "right_time_min": right_t,
        "W_at_level_min": W05,
        "f_leading_min": flead,
        "USP_tailing": tail,
        "apex_index": int(idx_max),
    }

def process_and_plot(input_path, out_dir,
                     bl_window=BASELINE_WINDOW_POINTS,
                     smooth_window=SMOOTH_WINDOW_POINTS,
                     frac=TAILING_FRACTION):
    os.makedirs(out_dir, exist_ok=True)
    plots_dir = os.path.join(out_dir, "plots")
    os.makedirs(plots_dir, exist_ok=True)

    data = parse_compiled_chrom_file(input_path)
    if not data:
        raise RuntimeError(f"No chromatograms parsed from {input_path}.")

    summary_rows = []
    for fname, df in data.items():
        t = df["time_min"].values
        y = df["intensity"].values

        # Baseline correction + smoothing
        base     = rolling_min_baseline(y, window=bl_window)
        y_corr   = np.maximum(y - base, 0.0)
        y_smooth = smooth_ma(y_corr, window=smooth_window)

        # Metrics
        met = usp_tailing(t, y_smooth, frac=frac)
        if met is None:
            continue

        # ---------- PLOT (colored, clean, with NL + RT label; extra headroom) ----------
        fig, ax = plt.subplots(figsize=(8, 4.5))

        color = next(COLOR_CYCLE)
        ax.plot(t, y_smooth, linewidth=1.6, color=color)

        # Add headroom so the RT label doesn't collide
        ymax = float(np.max(y_smooth))
        apex_y = float(met["apex_height"])
        ax.set_ylim(top=max(ymax, apex_y) * 1.25)

        # Apex RT label above the peak
        ax.annotate(
            f"RT {met['apex_time_min']:.2f} min",
            xy=(met["apex_time_min"], met["apex_height"]),
            xytext=(0, 14),
            textcoords="offset points",
            ha="center",
            va="bottom",
            fontsize=10,
        )

        # Top-right box with intensity as NL and USP TF
        ax.text(
            0.98, 0.98,
            f"NL: {met['apex_height']:.2E}\nUSP TF: {met['USP_tailing']:.2f}",
            transform=ax.transAxes,
            ha="right",
            va="top",
            fontsize=10,
            bbox=dict(boxstyle="round", fc="white", alpha=0.65, lw=0),
        )

        # Title using helper
        title_text = pretty_title(
            fname,
            df["inferred_pH"].iloc[0] if "inferred_pH" in df.columns else None,
            df["series"].iloc[0] if "series" in df.columns else ""
        )
        ax.set_title(title_text)
        ax.set_xlabel("Time (min)")
        ax.set_ylabel("Intensity (a.u.)")
        # Optional: avoid 1e6 scientific scaling on y-axis ticks
        # ax.ticklabel_format(style="plain", axis="y")
        fig.tight_layout()

        out_png = os.path.join(plots_dir, f"{os.path.splitext(fname)[0]}_chrom.png")
        fig.savefig(out_png, dpi=150)
        plt.close(fig)
        # -------------------------------------------------------------------

        # Summary row
        row = {
            "source_file": fname,
            "inferred_pH": df["inferred_pH"].iloc[0],
            "series": df["series"].iloc[0] if "series" in df.columns else "",
        }
        row.update(met)
        summary_rows.append(row)

    summary = pd.DataFrame(summary_rows)
    out_csv = os.path.join(out_dir, "summary.csv")
    summary.to_csv(out_csv, index=False)
    return out_csv, plots_dir

# ---------- RUN ----------
os.makedirs(OUTPUT_BASEDIR, exist_ok=True)
for path in INPUT_FILES:
    tag = os.path.splitext(os.path.basename(path))[0]
    out_dir = os.path.join(OUTPUT_BASEDIR, tag)
    try:
        summary_csv, plots_dir = process_and_plot(path, out_dir)
        print(f"[OK] {path}")
        print(f"  Summary: {summary_csv}")
        print(f"  Plots:   {plots_dir}")
    except Exception as e:
        print(f"[ERROR] {path}: {e}")

"""OVERLAYED MEDRONIC ACID TRIPLICATED 5 mM - Figure 8

"""

import os, re
import numpy as np
import matplotlib.pyplot as plt

# ---------------- USER KNOBS ----------------
NORMALIZE_TO_MAX = True      # True = scale each trace to its own max (makes overlay comparable)
PEAK_MARGIN_MIN  = 0.20      # minutes added to left/right peak bounds for x-axis
MAX_TRACES       = 3         # should be 3 (med1/med2/med3)
# -------------------------------------------

def parse_med_index_from_filename(fname: str):
    """
    Robustly extract med index from filenames like:
    '..._med1.csv', '...med2...', '...MED3...'
    Prefer the last occurrence to avoid earlier 'med' strings in folders.
    """
    base = os.path.basename(str(fname))
    hits = re.findall(r'(?i)med\s*([0-9]+)', base)
    return int(hits[-1]) if hits else None

def process_trace(df, bl_window=BASELINE_WINDOW_POINTS, smooth_window=SMOOTH_WINDOW_POINTS):
    t = df["time_min"].values
    y = df["intensity"].values
    base     = rolling_min_baseline(y, window=bl_window)
    y_corr   = np.maximum(y - base, 0.0)
    y_smooth = smooth_ma(y_corr, window=smooth_window)
    return t, y_smooth

def make_overlay_zoom_peaks(data, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    plots_dir = os.path.join(out_dir, "plots")
    os.makedirs(plots_dir, exist_ok=True)

    if not data:
        raise RuntimeError("No chromatograms parsed (empty dataset).")

    # --- Select med1/med2/med3 specifically (not "first 3 alphabetically") ---
    picked = []
    for fname, df in data.items():
        med_idx = parse_med_index_from_filename(fname)
        if med_idx is not None:
            picked.append((med_idx, fname, df))

    if not picked:
        raise RuntimeError("Could not find any files with 'med<number>' in the filename.")

    picked.sort(key=lambda x: x[0])  # med1, med2, med3, ...

    # keep only first 3 unique med indices
    selected = []
    seen = set()
    for med_idx, fname, df in picked:
        if med_idx in seen:
            continue
        selected.append((med_idx, fname, df))
        seen.add(med_idx)
        if len(selected) >= MAX_TRACES:
            break

    if len(selected) < 2:
        raise RuntimeError(f"Only found {len(selected)} med-indexed chromatograms; expected 3 (med1/med2/med3).")

    colors = ["tab:blue", "tab:orange", "tab:green"]

    traces = []
    lefts, rights = [], []

    # --- Process and find peak bounds for each trace ---
    for i, (med_idx, fname, df) in enumerate(selected):
        t, y = process_trace(df)

        met = usp_tailing(t, y, frac=TAILING_FRACTION)
        if met is None:
            continue

        # peak bounds at the chosen fraction (5% by default)
        left_t  = met["left_time_min"]
        right_t = met["right_time_min"]

        # store for global x-lims
        lefts.append(left_t)
        rights.append(right_t)

        # optional normalization for overlay comparison
        y_plot = y.copy()
        if NORMALIZE_TO_MAX:
            m = float(np.max(y_plot))
            if m > 0:
                y_plot = y_plot / m

        traces.append({
            "med_idx": med_idx,
            "fname": fname,
            "t": t,
            "y": y_plot,
            "rt": met["apex_time_min"],
            "color": colors[i % len(colors)],
        })

    if not traces:
        raise RuntimeError("No usable peaks detected after processing.")

    # --- Auto-zoom limits from peak bounds across all traces ---
    x_min = float(min(lefts) - PEAK_MARGIN_MIN)
    x_max = float(max(rights) + PEAK_MARGIN_MIN)

    # y max within the zoom window
    y_zoom_max = 0.0
    for tr in traces:
        mask = (tr["t"] >= x_min) & (tr["t"] <= x_max)
        if np.any(mask):
            y_zoom_max = max(y_zoom_max, float(np.max(tr["y"][mask])))

    if y_zoom_max <= 0:
        y_zoom_max = max(float(np.max(tr["y"])) for tr in traces)

    # --- Plot ---
    fig, ax = plt.subplots(figsize=(9, 5))

    for tr in traces:
        label = f"Sample {tr['med_idx']} (RT {tr['rt']:.2f})"
        ax.plot(tr["t"], tr["y"], linewidth=2.2, color=tr["color"], label=label)

        # RT label directly above apex
        apex_idx = int(np.argmax(tr["y"]))
        apex_x = float(tr["t"][apex_idx])
        apex_y = float(tr["y"][apex_idx])

        # Only annotate if apex is inside the zoom window
        if x_min <= apex_x <= x_max:
            ax.annotate(
                f"{tr['rt']:.2f}",
                xy=(apex_x, apex_y),
                xytext=(0, 10),
                textcoords="offset points",
                ha="center", va="bottom",
                fontsize=10,
                color=tr["color"]
            )

    ax.set_title(f"{MEDRONIC_CONC_LABEL} - Overlay (peaks, zoomed)")
    ax.set_xlabel("Time (min)")
    ax.set_ylabel("Intensity (norm.)" if NORMALIZE_TO_MAX else "Intensity (a.u.)")

    ax.set_xlim(x_min, x_max)
    ax.set_ylim(0, y_zoom_max * 1.12)

    ax.legend(loc="upper right", frameon=True)
    fig.tight_layout()

    out_png = os.path.join(plots_dir, "overlay_zoom_peaks.png")
    fig.savefig(out_png, dpi=200)
    plt.close(fig)

    return out_png, selected

# ---------- RUN ----------
dataset_tag = os.path.splitext(os.path.basename(DATA_PATH))[0]
out_dir = os.path.join(OUTPUT_BASEDIR, dataset_tag)

data = parse_compiled_csv_numeric(DATA_PATH)
overlay_png, selected = make_overlay_zoom_peaks(data, out_dir)

print("[OK] Overlay saved:", overlay_png)
print("Selected files:")
for med_idx, fname, _ in selected:
    print(f"  med{med_idx}: {fname}")

"""MULTIPLE MEDRONIC ACID INJECTIONS - Figure 9

"""

from google.colab import files
uploaded = files.upload()  # choose merged_raw_data.csv again

import pandas as pd
df = pd.read_csv('merged_raw_data.csv')
df.head()

import os, re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

# ---------- PARAMS (tweak as needed) ----------
DATA_PATH = 'merged_raw_data.csv'   # or 'Resultat colab/merged_raw_data.csv'
USE_BASELINE = True                 # subtract baseline (asymmetric least squares)
BASE_LAMBDA = 1e5                   # larger -> smoother baseline (1e4–1e7 typical)
BASE_P = 0.001                      # asymmetry (0.001–0.01)
BASE_NITER = 10                     # iterations for baseline fit
SMOOTH_WIN = 21                     # odd int
SMOOTH_POLY = 3                     # poly order for savgol (<= SMOOTH_WIN-1)
OUTPUT_DIR = 'plots_runs'           # folder for per-run PNGs
# ---------------------------------------------

INJECTION_LABELS = [
    "In-sample & blank 1.0, testID20",
    "In-sample & blank 1.0, testID21",
    "In-sample & blank 1.0, testID22",
    "In-sample 0.5, testID14",
    "In-sample 0.5, testID15",
    "In-sample 0.5, testID16",
    "In-sample 0.5, testID17",
    "In-sample & blank 0.5, testID18",
    "In-sample & blank 0.5, testID19",
]
# -----------------------------------------------

group_cols = ['source_file','medium','replicate','pH','std','date']

# 1) Load merged file
df = pd.read_csv(DATA_PATH)

# 2) Parse CHROMATOGRAM column into numeric arrays per run
num_pair_re = re.compile(
    r'^\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)\s*,\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)\s*$'
)

runs = []
for keys, g in df.groupby(group_cols, dropna=False):
    times, intens = [], []
    for val in g['CHROMATOGRAM'].astype(str):
        m = num_pair_re.match(val)
        if m:
            times.append(float(m.group(1)))
            intens.append(float(m.group(2)))
    if times:
        run = pd.DataFrame({
            'time_min': np.array(times, dtype=float),
            'intensity_raw': np.array(intens, dtype=float),
        }).sort_values('time_min')
        for col, v in zip(group_cols, keys):
            run[col] = v
        runs.append(run)

if not runs:
    raise RuntimeError("No numeric chromatogram points parsed. Check column 'CHROMATOGRAM' and file path.")

chrom = pd.concat(runs, ignore_index=True)

# Optional normalization (prevents accidental group drops if there are NaNs)
chrom['medium']    = chrom['medium'].fillna('no-med')
chrom['replicate'] = chrom['replicate'].fillna(1).astype(int)

# 3) Smoothing + Baseline removal -------------------------------------------
def moving_average(y, w):
    w = max(1, int(w))
    if w % 2 == 0:
        w += 1
    pad = w // 2
    ypad = np.pad(y, (pad, pad), mode='edge')
    kernel = np.ones(w) / w
    return np.convolve(ypad, kernel, mode='valid')

def asls_baseline(y, lam=1e5, p=0.001, niter=10):
    """Asymmetric least squares baseline (Eilers & Boelens)."""
    y = np.asarray(y, float)
    L = len(y)
    if L < 3:
        return np.zeros_like(y)
    D = np.diff(np.eye(L), 2, axis=0)   # (L-2 x L)
    w = np.ones(L)
    for _ in range(niter):
        W = np.diag(w)
        Z = W + lam * (D.T @ D)
        z = np.linalg.solve(Z, W @ y)
        w = p * (y > z) + (1 - p) * (y < z)
    return z

def clean_signal(y):
    """Smoothing + baseline removal with safety for short series."""
    y = np.asarray(y, float)
    # smoothing (savgol if available)
    try:
        from scipy.signal import savgol_filter
        win = int(SMOOTH_WIN)
        if win % 2 == 0:
            win += 1
        win = min(win, len(y) - (1 - len(y) % 2)) if len(y) > 3 else 3
        win = max(win, 3)
        if win % 2 == 0:
            win = max(3, win - 1)
        poly = min(int(SMOOTH_POLY), win - 1)
        ys = savgol_filter(y, window_length=win, polyorder=poly, mode='interp')
    except Exception:
        ys = moving_average(y, SMOOTH_WIN)

    # baseline
    if USE_BASELINE and len(y) >= 5:
        base = asls_baseline(ys, lam=BASE_LAMBDA, p=BASE_P, niter=BASE_NITER)
    else:
        base = np.zeros_like(ys)

    yc = ys - base
    yc[yc < 0] = 0.0
    return ys, base, yc

cleaned_runs = []
for keys, g in chrom.groupby(group_cols, dropna=False):
    g = g.sort_values('time_min')
    ys, base, yc = clean_signal(g['intensity_raw'].values)
    gg = g.copy()
    gg['intensity_smooth'] = ys
    gg['baseline'] = base
    gg['intensity_clean'] = yc
    cleaned_runs.append(gg)

chrom_clean = pd.concat(cleaned_runs, ignore_index=True)
chrom_clean['medium']    = chrom_clean['medium'].fillna('no-med')
chrom_clean['replicate'] = chrom_clean['replicate'].fillna(1).astype(int)

# 4) Metrics on CLEANED signal (NL, RT, TF) ----------------------------------
def peak_metrics(t, y):
    """
    RT = time at apex (argmax of cleaned signal)
    NL = apex intensity
    TF = USP tailing factor at 5%
    """
    t = np.asarray(t, float)
    y = np.asarray(y, float)
    if t.size < 3 or np.nanmax(y) <= 0:
        return dict(nl=np.nan, rt=np.nan, tf=np.nan)

    imax = int(np.nanargmax(y))
    nl = float(y[imax])
    rt = float(t[imax])  # <-- RT per injection (apex)

    level = 0.05 * nl  # 5%

    # left crossing
    t_left = np.nan
    for i in range(imax - 1, -1, -1):
        if y[i] <= level <= y[i + 1]:
            x0, y0 = t[i], y[i]
            x1, y1 = t[i + 1], y[i + 1]
            frac = 0 if y1 == y0 else (level - y0) / (y1 - y0)
            t_left = float(x0 + frac * (x1 - x0))
            break

    # right crossing
    t_right = np.nan
    for i in range(imax, len(y) - 1):
        if y[i] >= level >= y[i + 1]:
            x0, y0 = t[i], y[i]
            x1, y1 = t[i + 1], y[i + 1]
            frac = 0 if y1 == y0 else (level - y0) / (y1 - y0)
            t_right = float(x0 + frac * (x1 - x0))
            break

    if not (np.isnan(t_left) or np.isnan(t_right)) and t_right > t_left and rt > t_left:
        w05 = t_right - t_left
        f = rt - t_left
        tf = w05 / (2.0 * f) if f > 0 else np.nan
    else:
        tf = np.nan

    return dict(nl=nl, rt=rt, tf=tf)

metrics = []
for keys, g in chrom_clean.groupby(group_cols, dropna=False):
    g = g.sort_values('time_min')
    m = peak_metrics(g['time_min'].values, g['intensity_clean'].values)
    row = {col: val for col, val in zip(group_cols, keys)}
    row.update({
        'RT_min': m['rt'],  # <-- RT per injection
        'NL': m['nl'],
        'TF_5pct': m['tf'],
    })
    metrics.append(row)

metrics_df = pd.DataFrame(metrics)
if metrics_df.empty:
    raise RuntimeError("Metrics table is empty — check parsing and baseline parameters.")

# ---- INJECTION ORDER (controls inj_01, inj_02, ...) ----
metrics_df = metrics_df.sort_values(
    ['date', 'source_file', 'medium', 'replicate', 'pH', 'std'],
    na_position='last'
).reset_index(drop=True)

# Assign injection ids
metrics_df['inj_id'] = [f"inj_{i:02d}" for i in range(1, len(metrics_df) + 1)]

# Apply your labels by injection order
def _inj_label_for_row(idx, inj_id):
    if idx < len(INJECTION_LABELS) and str(INJECTION_LABELS[idx]).strip():
        return str(INJECTION_LABELS[idx]).strip()
    return inj_id

metrics_df['run_label'] = [
    _inj_label_for_row(i, inj) for i, inj in enumerate(metrics_df['inj_id'])
]

# Format helpers
def fmt_num(x, fmt="{:.2E}", nan="NA"):
    try:
        if x is None or (isinstance(x, float) and np.isnan(x)):
            return nan
        return fmt.format(float(x))
    except Exception:
        return nan

def fmt_float(x, fmt="{:.2f}", nan="NA"):
    try:
        if x is None or (isinstance(x, float) and np.isnan(x)):
            return nan
        return fmt.format(float(x))
    except Exception:
        return nan

# Lookup metrics/labels by full run identity (not just source_file)
m_lookup = (
    metrics_df
    .set_index(group_cols)[['RT_min','NL','TF_5pct','inj_id','run_label']]
    .to_dict('index')
)

# 5) Combined plot (all runs) with shared axes + RT BEFORE NL ----------------
xmin = float(chrom_clean['time_min'].min())
xmax = float(chrom_clean['time_min'].max())
ymin = 0.0
ymax = float(chrom_clean['intensity_clean'].max())

plt.figure(figsize=(10, 6))
for keys, g in chrom_clean.groupby(group_cols, dropna=False):
    g = g.sort_values('time_min')
    rk = tuple(keys)
    met = m_lookup.get(rk, {})
    rt = met.get('RT_min', np.nan)
    nl = met.get('NL', np.nan)
    tf = met.get('TF_5pct', np.nan)
    run_label = met.get('run_label', met.get('inj_id', 'inj'))

    # RT is displayed BEFORE NL (as you asked)
    label = f"{run_label} | RT {fmt_float(rt)} min, NL {fmt_num(nl)}, TF {fmt_float(tf)}"
    plt.plot(g['time_min'].values, g['intensity_clean'].values, label=label)

plt.xlim(xmin, xmax)
plt.ylim(ymin, ymax * 1.05)
plt.xlabel("Time (min)")
plt.ylabel("Intensity")
plt.title("Various conditions - in-sample injections")
plt.legend(loc='upper right', fontsize=7, framealpha=0.9)
plt.tight_layout()
combined_png = "chromatograms_all_runs_clean.png"
plt.savefig(combined_png, dpi=200)
plt.close()
print("Saved combined figure:", combined_png)

# 6) One plot per run + top-right textbox (RT before NL) ---------------------
os.makedirs(OUTPUT_DIR, exist_ok=True)

def safe_filename(s):
    return re.sub(r'[^A-Za-z0-9._-]+', '_', str(s)).strip('_')

for keys, g in chrom_clean.groupby(group_cols, dropna=False):
    g = g.sort_values('time_min')
    rk = tuple(keys)
    met = m_lookup.get(rk, {})
    rt = met.get('RT_min', np.nan)
    nl = met.get('NL', np.nan)
    tf = met.get('TF_5pct', np.nan)
    run_label = met.get('run_label', met.get('inj_id', 'inj'))

    plt.figure(figsize=(9, 5))
    plt.plot(g['time_min'], g['intensity_raw'], alpha=0.35, label='raw')
    plt.plot(g['time_min'], g['intensity_smooth'], linestyle='--', alpha=0.65, label='smoothed')
    if USE_BASELINE:
        plt.plot(g['time_min'], g['baseline'], alpha=0.8, label='baseline')
    plt.plot(g['time_min'], g['intensity_clean'], label='clean', linewidth=2)

    plt.xlabel("Time (min)")
    plt.ylabel("Intensity (a.u.)")
    plt.title(run_label)

    ax = plt.gca()
    ax.text(
        0.98, 0.98,
        f"RT: {fmt_float(rt)} min\nNL: {fmt_num(nl)}\nTF: {fmt_float(tf)}",
        transform=ax.transAxes, ha="right", va="top",
        fontsize=10, bbox=dict(boxstyle="round", fc="white", alpha=0.75, lw=0)
    )

    plt.legend(loc='upper left', fontsize=8)
    plt.tight_layout()
    fname = Path(OUTPUT_DIR) / f"{safe_filename(run_label)}_clean.png"
    plt.savefig(fname, dpi=200)
    plt.close()

print(f"Saved individual plots to: {OUTPUT_DIR}/")

# 7) Save cleaned table + metrics --------------------------------------------
chrom_clean.to_csv("chrom_cleaned_long.csv", index=False)
metrics_df.to_csv("chrom_metrics_clean.csv", index=False)
print("Saved cleaned data -> chrom_cleaned_long.csv")
print("Saved metrics -> chrom_metrics_clean.csv")

# Optional: print mapping so you can verify label assignment
print("\nInjection mapping (inj_id -> run_label):")
print(metrics_df[['inj_id','run_label','source_file','medium','replicate','pH','std','date']].to_string(index=False))

"""MOBILE PHASE MEDRONIC ACID SPIKING Figure 10"""

from google.colab import files
uploaded = files.upload()  # choose phytate_compiled_dataset_w_meta.csv again

import pandas as pd
df = pd.read_csv('phytate_compiled_dataset_w_meta.csv')
df.head()

import os, re
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ------------ params ------------
DATA_PATH   = "phytate_compiled_dataset_w_meta.csv"   # use your _w_meta file
OUTPUT_DIR  = "plots_runs_fast"
SMOOTH_WIN  = 21      # odd
SMOOTH_POLY = 3
BASE_MINWIN = 301     # odd; wide rolling-min window
BASE_MEDWIN = 101     # odd; median polish window
# --------------------------------

INJECTION_LABELS = [
    "Triplicate injection 1, testID23",
    "Triplicate injection 2, testID24",
    "Triplicate injection 3, testID25",
]
# ------------------------------------------------------

os.makedirs(OUTPUT_DIR, exist_ok=True)

# 1) Load
df = pd.read_csv(DATA_PATH)

# 2) Parse only "time,intensity" rows from CHROMATOGRAM and attach metadata
pair = re.compile(r'^\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)\s*,\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)\s*$')

group_cols = ['source_file','medium','replicate','pH','std','date']

runs = []
for (src, med, rep, ph, std, date), g in df.groupby(group_cols, dropna=False):
    ts, ys = [], []
    for s in g['CHROMATOGRAM'].astype(str):
        m = pair.match(s)
        if m:
            ts.append(float(m.group(1)))
            ys.append(float(m.group(2)))
    if ts:
        dd = pd.DataFrame({'time_min': ts, 'intensity_raw': ys}).sort_values('time_min')
        dd['source_file'] = src
        dd['medium']      = med
        dd['replicate']   = rep
        dd['pH']          = ph
        dd['std']         = std
        dd['date']        = date
        runs.append(dd)

if not runs:
    raise RuntimeError("No numeric pairs parsed. Check DATA_PATH and that column is named CHROMATOGRAM.")

chrom = pd.concat(runs, ignore_index=True)

# Normalize missing metadata so groupby doesn't drop groups
chrom['medium']    = chrom['medium'].fillna('no-med')
chrom['replicate'] = chrom['replicate'].fillna(1).astype(int)

print(f"[diag] parsed points total: {len(chrom):,}")
print("[diag] groups:", chrom.groupby(['source_file','medium','replicate'], dropna=False).ngroups)

# 3) Smoothing (Savitzky–Golay if available; else moving average)
def smooth_series(y, win=21, poly=3):
    y = np.asarray(y, float)
    if len(y) < 5:
        return y.copy()
    try:
        from scipy.signal import savgol_filter
        win = int(win) if int(win) % 2 == 1 else int(win) + 1
        win = max(5, min(win, len(y) - (1 - len(y) % 2)))
        if win % 2 == 0:
            win = max(5, win - 1)
        poly = min(int(poly), win - 1)
        return savgol_filter(y, win, poly, mode='interp')
    except Exception:
        w = max(5, int(win) | 1)  # odd
        w = min(w, len(y) - (1 - len(y) % 2))
        if w < 3:
            return y.copy()
        pad = w // 2
        ypad = np.pad(y, (pad, pad), mode='edge')
        k = np.ones(w) / w
        return np.convolve(ypad, k, mode='valid')

# 4) Fast baseline (rolling MIN then rolling MEDIAN)
def fast_baseline(y, win_min=301, win_med=101):
    y = np.asarray(y, float)
    if len(y) < 5:
        return np.zeros_like(y)
    s = pd.Series(y)

    # keep windows odd and <= series length
    max_odd = len(s) - (1 - len(s) % 2)  # largest odd <= len
    win_min = int(win_min) | 1
    win_med = int(win_med) | 1
    win_min = min(max_odd, max(51, win_min))
    win_med = min(max_odd, max(31, win_med))

    base = s.rolling(window=win_min, center=True, min_periods=1).min()
    base = base.rolling(window=win_med, center=True, min_periods=1).median()
    return base.values

# 5) Clean signal per run
cleaned = []
for keys, g in chrom.groupby(group_cols, dropna=False):
    g = g.sort_values('time_min')
    y  = g['intensity_raw'].to_numpy(dtype=float)
    ys = smooth_series(y, SMOOTH_WIN, SMOOTH_POLY)
    base = fast_baseline(ys, BASE_MINWIN, BASE_MEDWIN)
    yc = ys - base
    yc[yc < 0] = 0.0
    gg = g.copy()
    gg['intensity_smooth'] = ys
    gg['baseline']         = base
    gg['intensity_clean']  = yc
    cleaned.append(gg)

chrom_clean = pd.concat(cleaned, ignore_index=True)
chrom_clean['medium']    = chrom_clean['medium'].fillna('no-med')
chrom_clean['replicate'] = chrom_clean['replicate'].fillna(1).astype(int)

# 6) Metrics (NL, RT, USP TF at 5%)
def peak_metrics(t, y):
    t = np.asarray(t, float); y = np.asarray(y, float)
    if t.size < 3 or np.nanmax(y) <= 0:
        return dict(nl=np.nan, rt=np.nan, tf=np.nan)

    i  = int(np.nanargmax(y))
    nl = float(y[i])
    rt = float(t[i])  # apex RT (min)

    level = 0.05 * nl

    # left crossing
    tL = np.nan
    for k in range(i - 1, -1, -1):
        if y[k] <= level <= y[k + 1]:
            x0, y0 = t[k], y[k]
            x1, y1 = t[k + 1], y[k + 1]
            frac = 0 if y1 == y0 else (level - y0) / (y1 - y0)
            tL = float(x0 + frac * (x1 - x0))
            break

    # right crossing
    tR = np.nan
    for k in range(i, len(y) - 1):
        if y[k] >= level >= y[k + 1]:
            x0, y0 = t[k], y[k]
            x1, y1 = t[k + 1], y[k + 1]
            frac = 0 if y1 == y0 else (level - y0) / (y1 - y0)
            tR = float(x0 + frac * (x1 - x0))
            break

    tf = np.nan
    if not (np.isnan(tL) or np.isnan(tR)) and tR > tL and rt > tL:
        w05 = tR - tL
        f   = rt - tL
        tf  = w05 / (2.0 * f) if f > 0 else np.nan

    return dict(nl=nl, rt=rt, tf=tf)

rows = []
for keys, g in chrom_clean.groupby(group_cols, dropna=False):
    g = g.sort_values('time_min')
    m = peak_metrics(g['time_min'].values, g['intensity_clean'].values)
    row = {col: val for col, val in zip(group_cols, keys)}
    row.update({
        'NL': m['nl'],
        'RT_min': m['rt'],
        'USP_TF_5pct': m['tf'],
    })
    rows.append(row)

metrics_df = pd.DataFrame(rows)
if metrics_df.empty:
    raise RuntimeError("Metrics table is empty — check parsing and baseline parameters.")

# ---- INJECTION ORDER (controls inj_01, inj_02, ...) ----
metrics_df = metrics_df.sort_values(
    ['date', 'source_file', 'medium', 'replicate', 'pH', 'std'],
    na_position='last'
).reset_index(drop=True)

# Assign injection ids
metrics_df['inj_id'] = [f"inj_{i:02d}" for i in range(1, len(metrics_df) + 1)]

# your labels by injection order
def _inj_label_for_row(idx, inj_id):
    if idx < len(INJECTION_LABELS) and str(INJECTION_LABELS[idx]).strip():
        return str(INJECTION_LABELS[idx]).strip()
    return inj_id

metrics_df['run_label'] = [
    _inj_label_for_row(i, inj) for i, inj in enumerate(metrics_df['inj_id'])
]

# Format helpers (safe in case of NaN)
def fmt_num(x, fmt="{:.2E}", nan="NA"):
    try:
        if x is None or (isinstance(x, float) and np.isnan(x)):
            return nan
        return fmt.format(float(x))
    except Exception:
        return nan

def fmt_float(x, fmt="{:.2f}", nan="NA"):
    try:
        if x is None or (isinstance(x, float) and np.isnan(x)):
            return nan
        return fmt.format(float(x))
    except Exception:
        return nan

# Lookup metrics/labels by full run identity (internal)
m_lookup = (
    metrics_df
    .set_index(group_cols)[['NL','RT_min','USP_TF_5pct','inj_id','run_label']]
    .to_dict('index')
)

# 7) Combined overlay (shared axes) with NL, TF, RT in legend
xmin, xmax = float(chrom_clean['time_min'].min()), float(chrom_clean['time_min'].max())
ymax = float(chrom_clean['intensity_clean'].max())

plt.figure(figsize=(11, 6))
for keys, g in chrom_clean.groupby(group_cols, dropna=False):
    g = g.sort_values('time_min')
    rk = tuple(keys)
    met = m_lookup.get(rk, {})
    nl = met.get('NL', np.nan)
    tf = met.get('USP_TF_5pct', np.nan)
    rt = met.get('RT_min', np.nan)
    run_label = met.get('run_label', met.get('inj_id', 'inj'))

    label = f"{run_label} | NL {fmt_num(nl)}, TF {fmt_float(tf)}, RT {fmt_float(rt)} min"
    plt.plot(g['time_min'].values, g['intensity_clean'].values, label=label)

plt.xlim(xmin, xmax)
plt.ylim(0, ymax * 1.05)
plt.xlabel("Time (min)")
plt.ylabel("Intensity")
plt.title("Medronic acid in-buffer 0.5 uM")
plt.legend(loc='upper right', fontsize=7, framealpha=0.9)
plt.tight_layout()
combined_png = "chromatograms_all_runs_clean_fast.png"
plt.savefig(combined_png, dpi=200)
plt.close()

# 8) One plot per run (textbox shows NL/TF/RT)
def safe_filename(s):
    return re.sub(r'[^A-Za-z0-9._-]+', '_', str(s)).strip('_')

for keys, g in chrom_clean.groupby(group_cols, dropna=False):
    g = g.sort_values('time_min')
    rk = tuple(keys)
    met = m_lookup.get(rk, {})
    nl = met.get('NL', np.nan)
    tf = met.get('USP_TF_5pct', np.nan)
    rt = met.get('RT_min', np.nan)
    run_label = met.get('run_label', met.get('inj_id', 'inj'))

    plt.figure(figsize=(9, 5))
    plt.plot(g['time_min'], g['intensity_raw'],    alpha=0.35, label='raw')
    plt.plot(g['time_min'], g['intensity_smooth'], linestyle='--', alpha=0.65, label='smoothed')
    plt.plot(g['time_min'], g['baseline'],         alpha=0.8,  label='baseline')
    plt.plot(g['time_min'], g['intensity_clean'],  linewidth=2, label='clean')

    plt.xlabel("Time (min)")
    plt.ylabel("Intensity (a.u.)")
    plt.title(run_label)

    ax = plt.gca()
    ax.text(
        0.98, 0.98,
        f"NL: {fmt_num(nl)}\nUSP TF: {fmt_float(tf)}\nRT: {fmt_float(rt)} min",
        transform=ax.transAxes, ha="right", va="top",
        fontsize=10, bbox=dict(boxstyle="round", fc="white", alpha=0.75, lw=0)
    )

    plt.legend(loc='upper left', fontsize=8)
    plt.tight_layout()
    out_path = Path(OUTPUT_DIR) / f"{safe_filename(run_label)}_clean.png"
    plt.savefig(out_path, dpi=200)
    plt.close()

# 9) Save tables (metrics includes RT_min + labels)
chrom_clean.to_csv("chrom_cleaned_long_fast.csv", index=False)
metrics_df.to_csv("chrom_metrics_clean_fast.csv", index=False)

print("Saved:",
      combined_png + ",",
      f"{OUTPUT_DIR}/*_clean.png,",
      "chrom_cleaned_long_fast.csv,",
      "chrom_metrics_clean_fast.csv")

"""MEDRONIC ACID INJECTON 0.2 mM - Figure 11"""

from google.colab import files
uploaded = files.upload()  # choose ph88_merged_for_download.csv again

import pandas as pd
df = pd.read_csv('ph88_merged_for_download.csv')
df.head()

import os, re, math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

# ---------- PARAMS (tweak as needed) ----------
DATA_PATH = 'ph88_merged_for_download.csv'   # or 'Resultat colab/merged_raw_data.csv'
USE_BASELINE = True                 # subtract baseline (asymmetric least squares)
BASE_LAMBDA = 1e5                   # larger -> smoother baseline (1e4–1e7 typical)
BASE_P = 0.001                      # asymmetry (0.001–0.01)
BASE_NITER = 10                     # iterations for baseline fit
SMOOTH_METHOD = 'savgol'            # 'savgol' or 'moving'
SMOOTH_WIN = 21                     # odd int, number of points (~ adjust to your sampling)
SMOOTH_POLY = 3                     # poly order for savgol (<= SMOOTH_WIN-1)
OUTPUT_DIR = 'plots_runs'           # folder for per-run PNGs
# ---------------------------------------------

# 1) Load merged file
df = pd.read_csv(DATA_PATH)

# 2) Parse CHROMATOGRAM column into numeric arrays per run
num_pair_re = re.compile(
    r'^\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)\s*,\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)\s*$'
)

runs = []
for (src, med, rep, ph, std, date), g in df.groupby(
    ['source_file','medium','replicate','pH','std','date'], dropna=False
):
    times, intens = [], []
    for val in g['CHROMATOGRAM'].astype(str):
        m = num_pair_re.match(val)
        if m:
            times.append(float(m.group(1)))
            intens.append(float(m.group(2)))
    if times:
        run = pd.DataFrame({
            'time_min': np.array(times, dtype=float),
            'intensity_raw': np.array(intens, dtype=float),
        }).sort_values('time_min')
        run['source_file'] = src
        run['medium'] = med
        run['replicate'] = rep
        run['pH'] = ph
        run['std'] = std
        run['date'] = date
        runs.append(run)

if not runs:
    raise RuntimeError("No numeric chromatogram points parsed. Check column 'CHROMATOGRAM' and file path.")

chrom = pd.concat(runs, ignore_index=True)

# 3) Smoothing + Baseline removal -------------------------------------------
def moving_average(y, w):
    w = max(1, int(w))
    if w % 2 == 0: w += 1
    pad = w // 2
    ypad = np.pad(y, (pad, pad), mode='edge')
    kernel = np.ones(w) / w
    return np.convolve(ypad, kernel, mode='valid')

def savgol_safe(y, win, poly):
    # Try SciPy savgol (usually available), else fallback to moving average
    try:
        from scipy.signal import savgol_filter
        win = int(win) if int(win) % 2 == 1 else int(win) + 1
        poly = int(poly)
        win = max(poly+2 if (poly % 2 == 0) else poly+1, win)  # ensure win > poly and odd
        if win >= len(y):  # fallback if too short
            return moving_average(y, min(len(y)//2*2-1, 5) if len(y)>5 else 3)
        return savgol_filter(y, window_length=win, polyorder=poly, mode='interp')
    except Exception:
        return moving_average(y, win)

def asls_baseline(y, lam=1e5, p=0.001, niter=10):
    """
    Asymmetric least squares baseline (Eilers & Boelens), fixed axis.
    Returns baseline array the same length as y.
    """
    y = np.asarray(y, float)
    L = len(y)
    if L < 3:
        return np.zeros_like(y)

    # <-- FIX: take second difference along axis=0 so D has shape (L-2, L)
    D = np.diff(np.eye(L), 2, axis=0)            # (L-2 x L)
    w = np.ones(L)

    for _ in range(niter):
        W = np.diag(w)                           # (L x L)
        Z = W + lam * (D.T @ D)                  # (L x L)
        # Solve (W + lam * DᵀD) z = W y
        z = np.linalg.solve(Z, W @ y)
        # Update asymmetric weights
        w = p * (y > z) + (1 - p) * (y < z)

    return z

def clean_signal(y):
    """Smoothing + baseline removal with safety for short series."""
    y = np.asarray(y, float)
    # --- smoothing (same as before, but safer window) ---
    def moving_average(y, w):
        w = max(1, int(w));  w += (w % 2 == 0)   # force odd
        pad = w // 2
        ypad = np.pad(y, (pad, pad), mode='edge')
        k = np.ones(w) / w
        return np.convolve(ypad, k, mode='valid')

    try:
        from scipy.signal import savgol_filter
        win = int(SMOOTH_WIN) if int(SMOOTH_WIN) % 2 == 1 else int(SMOOTH_WIN) + 1
        win = min(win, len(y) - (1 - len(y) % 2)) if len(y) > 3 else 3
        win = max(win, 3)
        poly = min(int(SMOOTH_POLY), win - 1)
        ys = savgol_filter(y, window_length=win, polyorder=poly, mode='interp')
    except Exception:
        ys = moving_average(y, SMOOTH_WIN)

    # --- baseline ---
    if USE_BASELINE and len(y) >= 5:
        base = asls_baseline(ys, lam=BASE_LAMBDA, p=BASE_P, niter=BASE_NITER)
    else:
        base = np.zeros_like(ys)

    yc = ys - base
    yc[yc < 0] = 0.0
    return ys, base, yc


cleaned_runs = []
for keys, g in chrom.groupby(['source_file','medium','replicate','pH','std','date'], dropna=False):
    g = g.sort_values('time_min')
    ys, base, yc = clean_signal(g['intensity_raw'].values)
    gg = g.copy()
    gg['intensity_smooth'] = ys
    gg['baseline'] = base
    gg['intensity_clean'] = yc
    cleaned_runs.append(gg)

chrom_clean = pd.concat(cleaned_runs, ignore_index=True)

# 4) Metrics on CLEANED signal -----------------------------------------------
def peak_metrics(t, y):
    t = np.asarray(t, float)
    y = np.asarray(y, float)
    if t.size < 3 or np.nanmax(y) <= 0:
        return dict(max_intensity=np.nan, t_apex=np.nan, tailing_factor=np.nan)
    imax = int(np.nanargmax(y))
    y_max = float(y[imax]); t_apex = float(t[imax])
    level = 0.05 * y_max  # 5%

    # left crossing
    t_left = np.nan
    for i in range(imax-1, -1, -1):
        if y[i] <= level <= y[i+1]:
            x0, y0 = t[i], y[i]; x1, y1 = t[i+1], y[i+1]
            frac = 0 if y1==y0 else (level - y0)/(y1 - y0)
            t_left = float(x0 + frac*(x1 - x0)); break
    # right crossing
    t_right = np.nan
    for i in range(imax, len(y)-1):
        if y[i] >= level >= y[i+1]:
            x0, y0 = t[i], y[i]; x1, y1 = t[i+1], y[i+1]
            frac = 0 if y1==y0 else (level - y0)/(y1 - y0)
            t_right = float(x0 + frac*(x1 - x0)); break

    if not (np.isnan(t_left) or np.isnan(t_right)) and t_right > t_left and t_apex > t_left:
        w05 = t_right - t_left
        f = t_apex - t_left
        tail = w05 / (2.0 * f) if f > 0 else np.nan
    else:
        tail = np.nan
    return dict(max_intensity=y_max, t_apex=t_apex, tailing_factor=tail)

metrics = []
for (src, med, rep, ph, std, date), g in chrom_clean.groupby(
    ['source_file','medium','replicate','pH','std','date'], dropna=False
):
    g = g.sort_values('time_min')
    m = peak_metrics(g['time_min'].values, g['intensity_clean'].values)
    metrics.append({
        'source_file': src,
        'medium': med,
        'replicate': rep,
        'pH': ph,
        'std': std,
        'date': date,
        'max_intensity_clean': m['max_intensity'],
        't_apex_min': m['t_apex'],
        'tailing_factor_5pct_clean': m['tailing_factor'],
    })
metrics_df = pd.DataFrame(metrics).sort_values(['medium','replicate','source_file'])

# 5) Combined plot (all runs) with shared axes + NL & USP TF in legend
xmin = chrom_clean['time_min'].min()
xmax = chrom_clean['time_min'].max()
ymin = 0
ymax = chrom_clean['intensity_clean'].max()

# quick lookup from source_file -> (NL, TF)
m_lookup = (
    metrics_df
    .set_index('source_file')[['max_intensity_clean','tailing_factor_5pct_clean']]
    .to_dict('index')
)

plt.figure(figsize=(10,6))
for (src, med, rep), g in chrom_clean.groupby(['source_file','medium','replicate']):
    g = g.sort_values('time_min')
    met = m_lookup.get(src, {'max_intensity_clean':np.nan, 'tailing_factor_5pct_clean':np.nan})
    nl = met['max_intensity_clean']; tf = met['tailing_factor_5pct_clean']
    label = f"{Path(src).stem} | {med}, rep {rep} | NL {nl:.2E}, TF {tf:.2f}"
    plt.plot(g['time_min'].values, g['intensity_clean'].values, label=label)

plt.xlim(xmin, xmax)
plt.ylim(ymin, ymax*1.05)
plt.xlabel("Time (min)")
plt.ylabel("Intensity (cleaned)")
plt.title("Chromatograms — cleaned (shared axes)")
plt.legend(loc='upper right', fontsize=7, framealpha=0.9)
plt.tight_layout()
combined_png = "chromatograms_all_runs_clean.png"
plt.savefig(combined_png, dpi=200)
print("Saved combined figure:", combined_png)


# 6) One plot per run + top-right NL & USP TF textbox
os.makedirs(OUTPUT_DIR, exist_ok=True)

# reuse the same metrics lookup
m_lookup = (
    metrics_df
    .set_index('source_file')[['max_intensity_clean','tailing_factor_5pct_clean','t_apex_min']]
    .to_dict('index')
)

for (src, med, rep), g in chrom_clean.groupby(['source_file','medium','replicate']):
    g = g.sort_values('time_min')
    met = m_lookup.get(src, {'max_intensity_clean':np.nan, 'tailing_factor_5pct_clean':np.nan, 't_apex_min':np.nan})
    nl = met['max_intensity_clean']; tf = met['tailing_factor_5pct_clean']; rt = met['t_apex_min']

    plt.figure(figsize=(9,5))
    plt.plot(g['time_min'], g['intensity_raw'], alpha=0.35, label='raw')
    plt.plot(g['time_min'], g['intensity_smooth'], linestyle='--', alpha=0.65, label='smoothed')
    if USE_BASELINE:
        plt.plot(g['time_min'], g['baseline'], alpha=0.8, label='baseline')
    plt.plot(g['time_min'], g['intensity_clean'], label='clean', linewidth=2)

    # labels, title
    plt.xlabel("Time (min)"); plt.ylabel("Intensity (a.u.)")
    title = f"{Path(src).stem} | {med}, rep {rep}"
    plt.title(title)

    # top-right textbox with NL & TF (and RT if you want)
    ax = plt.gca()
    ax.text(
        0.98, 0.98,
        f"NL: {nl:.2E}\nUSP TF: {tf:.2f}\nRT: {rt:.2f} min",
        transform=ax.transAxes, ha="right", va="top",
        fontsize=10, bbox=dict(boxstyle="round", fc="white", alpha=0.75, lw=0)
    )

    plt.legend(loc='upper left', fontsize=8)
    plt.tight_layout()
    fname = Path(OUTPUT_DIR) / f"{Path(src).stem}_clean.png"
    plt.savefig(fname, dpi=200)
    plt.close()
print(f"Saved individual plots to: {OUTPUT_DIR}/")


# 7) Save cleaned table + metrics --------------------------------------------
chrom_clean.to_csv("chrom_cleaned_long.csv", index=False)
metrics_df.to_csv("chrom_metrics_clean.csv", index=False)
print("Saved cleaned data -> chrom_cleaned_long.csv")
print("Saved metrics -> chrom_metrics_clean.csv")

# Show metrics table in output
metrics_df

"""SUMMARY OF ALL MEDRONIC ACID EXPERIMENTS - Figure 12"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ------------------ Data for tests 11–29 ------------------
df = pd.DataFrame({
    "TestID": list(range(11, 30)),
    "RT": [
        # Tests 11–25 (original)
        7.20, 7.15, 7.13, 7.52, 7.47, 7.45, 7.46, 7.55, 7.79, 7.96,
        8.50, 8.97, 9.47, 12.49, 11.90,
        # Tests 26–29 (In-sample 0.2 mM; 4 injections)
        7.78, 7.94, 8.48, 8.89
    ],
    "NL": [
        # Tests 11–25 (original)
        5.06e6, 5.51e6, 6.51e6, 6.26e6, 4.92e6, 3.97e6, 2.19e6, 8.33e5, 3.35e5, 1.22e5,
        6.54e4, 3.22e4, 6.26e4, 1.28e4, 2.61e3,
        # Tests 26–29 (In-sample 0.2 mM; 4 injections)
        1.47e5, 1.04e5, 3.34e4, 1.98e4
    ],
    "USP_TF": [
        # Tests 11–25 (original)
        4.34, 3.07, 2.68, 3.33, 3.96, 4.94, 5.50, 5.62, 2.50, 3.01,
        1.20, 1.16, 1.28, 2.22, 0.90,
        # Tests 26–29 (In-sample 0.2 mM; 4 injections)
        2.05, 1.67, 1.27, 1.10
    ]
})

# ------------------ Assign groups (updated to include 0.2 mM) ------------------
def group_label(test_id):
    if 26 <= test_id <= 29:
        return "In-sample 0.2 mM"
    elif 11 <= test_id <= 17:
        return "In-sample 0.5 mM"
    elif 18 <= test_id <= 19:
        return "In-sample & blank 0.5 mM"
    elif 20 <= test_id <= 22:
        return "In-sample & blank 1.0 mM"
    elif 23 <= test_id <= 25:
        return "In mobile phase 0.5 µM"
    else:
        return np.nan

df["Group"] = df["TestID"].apply(group_label)
df["log10_NL"] = np.log10(df["NL"])
df = df.sort_values("TestID")

# ------------------ Palette (consistent across all plots) ------------------
palette = {
    "In-sample 0.2 mM":            "#2ca02c",  # green
    "In-sample 0.5 mM":            "#1f77b4",  # blue
    "In-sample & blank 0.5 mM":    "#ff7f0e",  # orange
    "In-sample & blank 1.0 mM":    "#d62728",  # red
    "In mobile phase 0.5 µM":      "#7B6CF6",  # purple
}
groups = list(palette.keys())

# ------------------ End-of-line labeling helper ------------------
def add_end_labels(ax, gdf, ycol, label, color, xpad=0.25, ypad=0.0):
    """Place a small text label at the last visible point of a line."""
    if gdf.empty:
        return
    x_last = gdf["TestID"].iloc[-1]
    y_last = gdf[ycol].iloc[-1]
    ax.text(
        x_last + xpad, y_last + ypad, label,
        color=color, fontsize=8, va="center"
    )

# Optional small vertical offsets if two labels collide visually:
label_offsets = {
    # "In-sample 0.2 mM": 0.00,
    # "In-sample 0.5 mM": 0.00,
    # "In-sample & blank 0.5 mM": 0.00,
    # "In-sample & blank 1.0 mM": 0.00,
    # "In mobile phase 0.5 µM": 0.00,
}

# ------------------ Generic plotter (no legend; end labels only) ------------------
def plot_metric_endlabels(ycol, ylabel, title, outfile, ylim=None):
    fig, ax = plt.subplots(figsize=(8.4, 4.8))
    for g in groups:
        gdf = df[df["Group"] == g]
        if gdf.empty:
            continue
        ax.plot(
            gdf["TestID"], gdf[ycol],
            marker="o", linewidth=2, color=palette[g]
        )
        add_end_labels(
            ax, gdf, ycol, g, palette[g],
            xpad=0.25, ypad=label_offsets.get(g, 0.0)
        )

    ax.set_xlabel("Injection")
    ax.set_ylabel(ylabel)
    if ylim is not None:
        ax.set_ylim(*ylim)

    # Extend x-limits slightly to make room for end labels
    x_min, x_max = df["TestID"].min(), df["TestID"].max()
    ax.set_xlim(x_min - 0.5, x_max + 2.5)

    ax.set_title(title)
    ax.grid(True, linestyle="--", alpha=0.3)
    plt.tight_layout()
    plt.savefig(outfile, dpi=300)
    plt.show()

# ------------------ Generate all three figures ------------------
plot_metric_endlabels(
    ycol="log10_NL",
    ylabel="log10(NL)",
    title="Signal vs Injection",
    outfile="medronic_logNL_vs_test.png"
)

plot_metric_endlabels(
    ycol="RT",
    ylabel="Retention Time (min)",
    title="RT vs Injection",
    outfile="medronic_RT_vs_test.png"
)

plot_metric_endlabels(
    ycol="USP_TF",
    ylabel="USP Tailing Factor",
    title="USP TF vs Injection",
    outfile="medronic_TF_vs_test.png"
)

print("Saved: medronic_logNL_vs_test.png, medronic_RT_vs_test.png, medronic_TF_vs_test.png")
print("\n0.2 mM points (TestID 26–29):")
print(df[df["TestID"].between(26, 29)][["TestID", "Group", "RT", "NL", "USP_TF"]])

"""Tabell av samtliga körningar

"""

from google.colab import files
uploaded = files.upload()  # choose phytate_compiled_dataset_w_meta.csv again

import pandas as pd
df = pd.read_csv('phytate_compiled_dataset_w_meta.csv')
df.head()

import os, re, glob
import pandas as pd
import numpy as np

# --- List your inputs (absolute paths or glob patterns are fine) ---
INPUT_FILES = [
    "phytate_compiled_dataset_w_meta.csv",
    "Phytic_acid_20250916073744_pH10_good.csv",
    "phytic_pH_screen_raw_compiled.csv",
    "phytic_pH88_med_series_compiled.csv",
    "phytic_pH88_triplicates_compiled.csv",
]
OUT_LONG = "phytate_all_runs_long.csv"

# ---- helpers ----
def expand_files(items):
    files = []
    for itm in items:
        matches = glob.glob(itm) if any(ch in itm for ch in "*?[]") else [itm]
        files.extend(matches)
    # keep only existing files
    return [f for f in files if os.path.exists(f)]

def read_any_csv(path):
    # robust reader: different separators + encodings, skip bad lines
    for sep in [",",";","\t"]:
        for enc in ["utf-8","latin-1"]:
            try:
                df = pd.read_csv(path, sep=sep, encoding=enc, on_bad_lines="skip", low_memory=False)
                if not df.empty:
                    return df
            except Exception:
                pass
    print(f"[warn] Could not read: {path} (skipping)")
    return None

def norm_cols(df):
    df = df.copy()
    df.columns = [re.sub(r"\s+","_",c.strip()).strip("_") for c in df.columns]
    return df

def parse_tokens_from_name(name):
    """Parse test_id, pH, medium, replicate, std, date from a run/inner name."""
    stem = os.path.splitext(os.path.basename(str(name)))[0]
    # tokens
    m_tid = re.search(r"testID(\d+)", stem, re.I)
    test_id = int(m_tid.group(1)) if m_tid else None
    m_ph = re.search(r"pH(\d+)", stem, re.I)
    pH = None
    if m_ph:
        tok = m_ph.group(1)
        pH = float(tok)/10 if len(tok)==2 else (float(tok)/100 if len(tok)==3 else float(tok))
    m_med = re.search(r"(med\d+)", stem, re.I)
    medium = m_med.group(1).lower() if m_med else None
    m_rep = re.search(r"(?:rep|_)(\d+)$", stem, re.I)
    replicate = int(m_rep.group(1)) if m_rep else None
    m_std = re.search(r"std(\d+)", stem, re.I)
    std = int(m_std.group(1)) if m_std else None
    m_date = re.search(r"(20\d{6})", stem)
    date = m_date.group(1) if m_date else None
    return dict(test_id=test_id, pH=pH, medium=medium, replicate=replicate, std=std, date=date)

def safe_series(df, name, length):
    if name in df.columns:
        s = df[name]
        # If it's all NaN or empty dtype that upsets combine_first, return NaNs instead
        if getattr(s, "empty", False) or s.isna().all():
            return pd.Series([np.nan]*length)
        return s
    return pd.Series([np.nan]*length)

# ---- merge with per-run identity preserved ----
files = expand_files(INPUT_FILES)
print("[info] Found files:", files)

frames = []
for container_path in files:
    df = read_any_csv(container_path)
    if df is None:             # unreadable -> skip
        continue
    df = norm_cols(df)
    container = os.path.basename(container_path)

    # locate inner per-run filename column if present
    inner_col = None
    for cand in ["source_file","run_file","inner_source","inner_file"]:
        if cand in df.columns:
            inner_col = cand
            break

    # ensure CHROMATOGRAM exists (string "time,intensity")
    if "CHROMATOGRAM" not in df.columns:
        for alt in ["Chromatogram","chromatogram","CHROM","trace","Trace"]:
            if alt in df.columns:
                df["CHROMATOGRAM"] = df[alt].astype(str)
                break
    if "CHROMATOGRAM" not in df.columns:
        print(f"[warn] No CHROMATOGRAM-like column in {container}; skipping")
        continue

    # base run name from inner source if present, else from container
    if inner_col:
        base_run = df[inner_col].astype(str).apply(lambda x: os.path.splitext(os.path.basename(x))[0])
    else:
        base_run = pd.Series([os.path.splitext(container)[0]]*len(df))

    # parse tokens from names row-by-row
    parsed = base_run.apply(parse_tokens_from_name)
    parsed_df = pd.DataFrame(list(parsed))

    # coalesce with columns in file if they exist & have any real values
    L = len(df)
    test_id  = parsed_df["test_id"].combine_first(safe_series(df, "test_id",  L))
    replicate= parsed_df["replicate"].combine_first(safe_series(df, "replicate",L))
    pH       = parsed_df["pH"].combine_first(safe_series(df, "pH",       L))
    medium   = parsed_df["medium"].combine_first(safe_series(df, "medium",   L))
    std      = parsed_df["std"].combine_first(safe_series(df, "std",      L))
    date     = parsed_df["date"].combine_first(safe_series(df, "date",     L))

    # build a unique run_id
    def build_run_id(b, t, r):
        parts = [str(b)]
        if pd.notna(t): parts.append(f"test{int(t)}")
        if pd.notna(r): parts.append(f"rep{int(r)}")
        return "__".join(parts)

    run_id = [build_run_id(b, t, r) for b, t, r in zip(base_run, test_id, replicate)]

    out = pd.DataFrame({
        "run_id": run_id,
        "container_file": container,
        "inner_source_file": base_run,
        "CHROMATOGRAM": df["CHROMATOGRAM"].astype(str),
        "test_id": test_id,
        "medium": medium.fillna("no-med"),
        "replicate": pd.to_numeric(replicate, errors="coerce").fillna(1).astype(int),
        "pH": pd.to_numeric(pH, errors="coerce"),
        "std": pd.to_numeric(std, errors="coerce"),
        "date": date,
    })

    frames.append(out)

if not frames:
    raise RuntimeError("No usable inputs were read. Check paths or mount Drive and update INPUT_FILES.")

merged_runs = pd.concat(frames, ignore_index=True)
merged_runs = merged_runs.drop_duplicates(subset=["run_id","CHROMATOGRAM"])  # keep unique trace rows
merged_runs.to_csv(OUT_LONG, index=False)

print(f"[ok] Saved per-run long table -> {OUT_LONG}")
print(f"     rows: {len(merged_runs):,} | unique runs: {merged_runs['run_id'].nunique():,}")
merged_runs.head(10)